---
kind: pipeline
type: docker
name: container-images

steps:

- name: build-go
  image: rancher/hardened-build-base:v1.17.5b7
  commands:
    - make all
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
      - tag

- name: build-and-publish-container-images
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: Dockerfile
    repo: rancher/ecm-distro-tools
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
