---
kind: pipeline
name: container-images

platform:
  os: linux
  arch: amd64

steps:
- name: build-go-apps
  image: rancher/hardened-build-base:v1.17.5b7
  commands:
  - make all

- name: docker-publish
  image: plugins/docker
  environment:
  settings:
    dockerfile: Dockerfile
    repo: "rancher/ecm-distro-tools"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
    - name: docker
      path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
