---
kind: pipeline
name: container-images

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/hardened-build-base:v1.17.5b7
  commands:
    - make all
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/master"
    event:
      - tag

- name: docker-publish
  image: plugins/docker
  environment:
  settings:
    dockerfile: Dockerfile
    repo: "rancher/ecm-distro-tools"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/master"
    event:
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
